---
# start up
start_up:
  # =================== running mode (select one of the three) ================== #
  mode: scratch      # three mode: test, resume, scratch
  resume_epoch: 0   # default to zero, if use the 'resume' mode, users need to set the epoch to resume.

  # ============================================================================= #

  model_name:   D2STGNN                                   # model name
  device:       cuda:0
  load_pkl:     False                                     # load serialized dataloader

# Data Processing
data_args:
  data_dir:       datasets/METR-LA                        # data path
  adj_data_path:  datasets/sensor_graph/adj_mx_la.pkl     # adj data path
  adj_type:       doubletransition                        # adj type to preprocessing

# Model Args
model_args:
  batch_size:   32
  num_feat:     1
  num_hidden:   32
  node_hidden:  10
  time_emb_dim: 10
  dropout:      0.1
  seq_length:   12
  k_t:          3
  k_s:          2
  gap:          3
  num_modalities: 2

# Optimization Args
optim_args:
  # adam optimizer
  lrate:          0.002                                   # learning rate
  print_model:    False
  wdecay:         1.0e-5                                  # weight decay of adam
  eps:            1.0e-8                                  # eps of adam
  # learning rate scheduler
  lr_schedule:    True                                    # if use learning rate scheduler
  lr_sche_steps:  [1, 30, 38, 46, 54, 62, 70, 80]         # steps where decay the learning rate
  lr_decay_ratio: 0.5                                     # learning rate decay rate
  # curriculum learning
  if_cl:          True                                    # if use curriculum learning
  cl_epochs:      6                                       # epochs of curriculum learning when to forecasting next time step
  output_seq_len: 12
  # warm up
  warm_epochs:    0                                       # epochs of warmming up
  # procedure
  epochs:         80                                      # total epoch numbers
  patience:       100                                     # patience for earlystopping
  seq_length:     12                                      # input & output seq length
