---
# start up
start_up:
  # # For test:
  # only_test:    True                                    # if true, or only test
  # resume:       True                                    # if resume
  # resume_epoch: 0
  # resume_best:  True                                    # resume best or resume last
  
  # # For resume
  # only_test:    False
  # resume:       True
  # resume_epoch: X
  # resume_best:  False
  
  # Training from scratch
  only_test:    False                                     # if true, or only test
  resume:       False                                     # if resume
  resume_epoch: 0
  resume_best:  False                                     # resume best or resume last
  
  model_name:   D2STGNN                                   # model name
  device:       cuda:0
  load_pkl:     False                                     # load serialized dataloader

# Data Processing
data_args:
  data_dir:       datasets/PEMS08                         # data path
  adj_data_path:  datasets/sensor_graph/adj_mx_08.pkl     # adj data path
  adj_type:       doubletransition                        # adj type to preprocessing

# Model Args
model_args:
  batch_size:   16
  num_feat:     1
  num_hidden:   32
  node_hidden:  10
  time_emb_dim: 10
  dropout:      0.1
  seq_length:   12
  k_t:          3
  k_s:          2
  gap:          3
  num_modalities: 2

# Optimization Args
optim_args:
  # adam optimizer
  lrate:          0.002                                   # learning rate
  print_model:    False
  wdecay:         1.0e-5                                  # weight decay of adam
  eps:            1.0e-8                                  # eps of adam
  # learning rate scheduler
  lr_schedule:    True                                    # if use learning rate scheduler
  lr_sche_steps:  [1, 30, 38, 46, 54, 200]                     # steps where decay the learning rate
  lr_decay_ratio: 0.5                                     # learning rate decay rate
  # curriculum learning
  if_cl:          True                                    # if use curriculum learning
  cl_epochs:      3                                       # epochs of curriculum learning when to forecasting next time step
  output_seq_len: 12
  # warm up
  warm_epochs:    30                                      # epochs of warmming up
  # procedure
  epochs:         300                                     # total epoch numbers
  patience:       100                                     # patience for earlystopping
  seq_length:     12                                      # input & output seq length
